import type { Section } from "./types";

export const article = {
  slug: `vtubing-starter-guide`,
  title: `VTubing Starter Guide: From Zero to Your First Stream`,
  description: `A friendly walk-through of the free tools, software and setup you need to rig your first character and go live.`,
  thumbnail: `/__l5e/assets-v1/dccf27e8-c71d-4cce-b693-23e691432d89/article-placeholder.jpg`,
  category: `streaming`,
  tags: [`vtubing`, `vtuber`, `live2d`, `vtube studio`, `obs`, `streaming setup`],
  content: [
    { type: "p", text: `VTubing isn't a passing trend anymore — it's a whole industry that thousands of creators join every month. Whether you want to live-stream, post on YouTube, or just hang out on Discord as a virtual character, this guide takes you step by step from nothing to your first successful broadcast.` },
    { type: "callout", title: `💡 What you'll learn`, text: `Picking the right model type, free software, camera and mic setup, wiring your model into OBS, lighting and audio tips, and the little secrets behind your first 100 followers.` },
    { type: "h2", text: `1. What is a VTuber and why did it blow up?` },
    { type: "p", text: `A VTuber is a creator who uses a 2D or 3D avatar instead of showing their real face. The character moves in real time and mirrors your facial expressions, head motion and hand gestures through face-tracking.` },
    { type: "p", text: `The reason for the explosion is creative freedom: you can be any character you imagine, protect your privacy, and express yourself without the pressure of being on camera. That opened the door for a huge group of creators who used to feel too shy to start.` },
    { type: "image", src: `/__l5e/assets-v1/dccf27e8-c71d-4cce-b693-23e691432d89/article-placeholder.jpg`, alt: `VTubing Starter Guide: From Zero to Your First Stream`, caption: `A typical anime-style VTuber model — this is what viewers see instead of your face.` },
    { type: "h2", text: `2. Picking a model type: Live2D or 3D?` },
    { type: "p", text: `This is the first big decision. Each has trade-offs, and the right answer depends on your budget, skill, and content style.` },
    { type: "h3", text: `Live2D (most popular for beginners)` },
    { type: "list", ordered: false, items: [`A 2D character drawn in an anime illustration style.`, `Much cheaper — you can start under $50, sometimes free.`, `Light on your computer, no powerful GPU required.`, `Limited when it comes to full body motion.`] },
    { type: "h3", text: `3D (for more advanced content)` },
    { type: "list", ordered: false, items: [`A full 3D character that can move in a wider space.`, `Needs full-body tracking or a mocap suit.`, `More expensive and demands a stronger PC.`, `Great for dancing, action games, or VR streams.`] },
    { type: "callout", title: `💡 Our tip for beginners`, text: `Start with Live2D. It's cheap, fast to learn, and almost every famous VTuber started there. You can graduate to 3D once your channel grows.` },
    { type: "h2", text: `3. The free software you'll need` },
    { type: "p", text: `Good news: you can start completely free. Here are the staples our community uses:` },
    { type: "list", ordered: true, items: [`VTube Studio — the main app for running a Live2D model and tracking your face (free on Steam).`, `OBS Studio — the world's most popular streaming software, 100% free.`, `VRoid Studio — create your own 3D model from scratch with no experience (free).`, `VSeeFace — a great alternative for running VRM-format 3D models.`, `Audacity — record and clean up your voice (free).`] },
    { type: "h2", text: `4. The physical setup` },
    { type: "image", src: `/__l5e/assets-v1/dccf27e8-c71d-4cce-b693-23e691432d89/article-placeholder.jpg`, alt: `VTubing Starter Guide: From Zero to Your First Stream`, caption: `A simple streaming setup: two monitors, a condenser mic, decent lighting. You don't need to buy everything at once.` },
    { type: "h3", text: `Camera` },
    { type: "p", text: `Any 720p webcam is plenty to start. The camera isn't shown to viewers — it's only used for tracking. Even your laptop's built-in camera will do.` },
    { type: "h3", text: `Microphone` },
    { type: "p", text: `This is your most important investment. Bad audio loses viewers faster than bad video. Something like the Fifine K669 or Maono PD200X gives you great quality at a very reasonable price.` },
    { type: "h3", text: `Lighting` },
    { type: "p", text: `A cheap ring light noticeably improves face-tracking accuracy, especially in dark rooms. Tracking runs through the camera, so better light equals smoother motion.` },
    { type: "h2", text: `5. Setting up VTube Studio, step by step` },
    { type: "image", src: `/__l5e/assets-v1/dccf27e8-c71d-4cce-b693-23e691432d89/article-placeholder.jpg`, alt: `VTubing Starter Guide: From Zero to Your First Stream`, caption: `The Live2D interface — the pink control points are what get linked to your facial expressions.` },
    { type: "list", ordered: true, items: [`Download VTube Studio from Steam for free.`, `Grab a sample model or buy one from a Live2D artist on Twitter/Booth.`, `Drop the model files into the Models folder inside VTube Studio.`, `Open the app, choose your model, and enable the camera.`, `Bind your facial movements to the model's hotkeys in the model settings.`, `Set the background to green so it's easy to key out in OBS.`] },
    { type: "h2", text: `6. Wiring VTube Studio into OBS` },
    { type: "p", text: `Once your model is ready, it's time to stream. The idea is simple: OBS captures the VTube Studio window, removes the green background, and overlays just your character on top of your content (game, screen, whatever).` },
    { type: "list", ordered: true, items: [`In OBS, add a new Window Capture source and pick VTube Studio.`, `Right-click the source > Filters > add a Chroma Key filter.`, `Pick the green color and tweak Similarity until the background fully disappears.`, `Resize and position your model wherever fits on screen.`, `Add more sources: the game, your mic, music, donation alerts.`] },
    { type: "callout", title: `💡 Performance tip`, text: `If your stream FPS drops, try lowering the VTube Studio camera resolution from 720p to 480p. Tracking doesn't need a high resolution but it eats CPU.` },
    { type: "h2", text: `7. Building your character (lore & personality)` },
    { type: "p", text: `The technical side is only 30% of being a successful VTuber. The other 70% is your personality. Before you stream, decide: what's your character's name? Their age? Their backstory? What do they love and hate? The clearer the character, the faster viewers get attached.` },
    { type: "quote", text: `Viewers don't follow a game — they follow an interesting person who happens to be playing one. Be that interesting person.`, cite: `The Veguto community` },
    { type: "h2", text: `8. Your first stream: priceless tips` },
    { type: "list", ordered: false, items: [`Talk even when no one is watching. Silence kills a stream.`, `Smile and react — tracking will carry your expressions to the model.`, `Read chat out loud and call viewers by name.`, `Don't get discouraged by low numbers at first. Everyone started at zero.`, `Stream on a regular schedule (at least 3× a week at the same time).`] },
    { type: "h2", text: `9. Next steps after the basics` },
    { type: "p", text: `Once you're comfortable streaming, level up: customize your model with extra outfits and accessories, add Twitch integrations that let chat interact with your model (throw items at you!), learn Live2D yourself to rig models for others, or even start your own little VTuber agency.` },
    { type: "h2", text: `Closing thoughts` },
    { type: "p", text: `VTubing is a long, fun journey. Don't compare your day one to someone else's year five, and don't wait for the perfect moment to begin. The most important step is the first one — download VTube Studio today, try a sample model, and record a one-minute test clip. The Veguto community is here to help on every step through Discord.` },
    { type: "callout", title: `💡 Got a question?`, text: `Join the Veguto Discord and drop your question in #vtubing-help — community members usually answer within minutes.` },
  ] as Section[],
};

export default article;
