// AUTO-AGGREGATED tag layer.
// Tag definition files (./<slug>.ts exporting `tag`) are generated by
// `bun run content:gen`, but everything here is also derived dynamically from
// the articles themselves — a brand new tag works with zero manual edits.
import type { TagMeta } from "./types";
import type { ArticleData } from "@/content/articles/types";

export type { TagMeta };

export const tagSlug = (tag: string) =>
  tag.toLowerCase().trim().replace(/\s+/g, "-").replace(/[^a-z0-9-]/g, "");

export const titleize = (tag: string) =>
  tag
    .trim()
    .split(/\s+/)
    .map((w) => (w.length > 3 ? w[0].toUpperCase() + w.slice(1) : w))
    .join(" ")
    .replace(/^./, (c) => c.toUpperCase());

// ---- Articles (globbed directly to avoid a circular import with articles/index.ts) ----
const articleModules = import.meta.glob<{ article: ArticleData }>(
  ["../articles/*.ts", "!../articles/index.ts", "!../articles/types.ts"],
  { eager: true },
);

const ARTICLES: ArticleData[] = Object.values(articleModules)
  .map((m) => m.article)
  .filter(Boolean);

// ---- Optional per-tag definition files (./<slug>.ts) ----
const tagModules = import.meta.glob<{ tag: TagMeta }>(
  ["./*.ts", "!./tags.ts", "!./types.ts"],
  { eager: true },
);

const TAG_OVERRIDES = new Map<string, TagMeta>(
  Object.values(tagModules)
    .map((m) => m.tag)
    .filter(Boolean)
    .map((t) => [t.slug, t]),
);

// ---- Derived registry ----
const counts = new Map<string, { label: string; count: number }>();
for (const a of ARTICLES) {
  for (const raw of a.tags ?? []) {
    const slug = tagSlug(raw);
    if (!slug) continue;
    const prev = counts.get(slug);
    counts.set(slug, { label: prev?.label ?? raw.trim(), count: (prev?.count ?? 0) + 1 });
  }
}

const buildMeta = (slug: string, label: string): TagMeta =>
  TAG_OVERRIDES.get(slug) ?? {
    slug,
    label,
    title: titleize(label),
    blurb: `Articles tagged “${label}”.`,
  };

export const TAG_LIST: (TagMeta & { count: number })[] = [...counts.entries()]
  .map(([slug, { label, count }]) => ({ ...buildMeta(slug, label), count }))
  .sort((a, b) => b.count - a.count || a.slug.localeCompare(b.slug));

export const TAGS: string[] = TAG_LIST.map((t) => t.slug);

export const TAG_META: Record<string, TagMeta> = Object.fromEntries(
  TAG_LIST.map(({ count: _count, ...meta }) => [meta.slug, meta]),
);

export const isTagSlug = (slug: string) => Boolean(TAG_META[slug]);

export const getTagMeta = (slug: string): TagMeta | undefined => TAG_META[slug];

export const allTags = () => TAG_LIST.map(({ label, slug, count }) => ({ tag: label, slug, count }));

export const articlesByTagSlug = (slug: string) =>
  ARTICLES.filter((a) => (a.tags ?? []).some((t) => tagSlug(t) === slug));

// ---- Categories derived from articles (used to detect missing category defs) ----
export const ARTICLE_CATEGORY_IDS: string[] = [
  ...new Set(ARTICLES.map((a) => a.category).filter(Boolean)),
].sort();